version: 2

sources:
  - name: finance
    schema: raw
    tables:
      - name: raw_fx_rates
        identifier: fx_rates_timeseries
      
      - name: raw_stock_price
        identifier:  stock_price_timeseries