-- Use an admin role--
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS FINANCE;
CREATE SCHEMA IF NOT EXISTS FINANCE.RAW;

CREATE TABLE FX_RATES_TIMESERIES AS 
SELECT * FROM FINANCE_ECONOMICS.CYBERSYN.FX_RATES_TIMESERIES;

CREATE TABLE STOCK_PRICE_TIMESERIES AS 
SELECT * FROM FINANCE_ECONOMICS.CYBERSYN.STOCK_PRICE_TIMESERIES;

-- Use an admin role--
USE ROLE ACCOUNTADMIN;

-- Create the `transform` role
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='FINANCE.RAW'
  COMMENT='DBT user used for data transformation';
GRANT ROLE TRANSFORM to USER dbt;


-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM; 
GRANT ALL ON DATABASE FINANCE to ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE FINANCE to ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE FINANCE to ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA FINANCE.RAW to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA FINANCE.RAW to ROLE TRANSFORM;